Description:  AWS Systems Manager, with VPC Endpoint
Parameters:
  KeyPairName:
    Description: KeyPair for Instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: "A4L"
  WindowsAMI:
    Description: AMI for Windows Server
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: "/aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base"
  UbuntuAMI:
    Description: AMI For Ubuntu
    Type: String
    Default: "ami-03a2cbdcd9e7d1955"
  CentosAMI:
    Description: AMI For Centos
    Type: String
    Default: "ami-01ca03df4a6012157"
  AmazonLinux2AMI:
    Description: AMI for Bastion Host (default is latest AmaLinux2)
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
Resources:
  AWSVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.16.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: aws-vpc
  AWSIGW:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
      - Key: Name
        Value: IGW-AWS
  AWSIGWAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref AWSVPC
      InternetGatewayId: !Ref AWSIGW
  AWSSNPrivate:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AWSVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.16.0.0/24
      Tags:
        - Key: Name
          Value: sn-aws-private
  AWSSNPublic:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref AWSVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.16.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: sn-aws-public
  AWSRTPublic: 
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref AWSVPC
      Tags:
      - Key: Name
        Value: AWS-RT-PUBLIC
  AWSRTPublicAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref AWSSNPublic
      RouteTableId:
        Ref: AWSRTPublic
  AWSRTPrivate: 
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref AWSVPC
      Tags:
      - Key: Name
        Value: AWS-RT-PRIVATE
  AWSRTPrivateAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref AWSSNPrivate
      RouteTableId:
        Ref: AWSRTPrivate
  AWSRouteDefaultPublic: 
    Type: 'AWS::EC2::Route'
    DependsOn: AWSIGWAttachment
    Properties:
      RouteTableId:
        Ref: AWSRTPublic
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId:
        Ref: AWSIGW
  AWSEIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
  AWSNATGW:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !GetAtt AWSEIP.AllocationId
      SubnetId: !Ref AWSSNPublic
  AWSRouteDefaultPrivate: 
    Type: 'AWS::EC2::Route'
    DependsOn: AWSIGWAttachment
    Properties:
      RouteTableId:
        Ref: AWSRTPrivate
      DestinationCidrBlock: '0.0.0.0/0'
      NatGatewayId:
        Ref: AWSNATGW
  AWSInstanceSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref AWSVPC
      GroupDescription: Default A4L AWS SG
      SecurityGroupIngress: 
        - Description: 'Allow SSH IPv4 IN'
          IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
        - Description: 'Allow RDP IPv4 IN'
          IpProtocol: tcp
          FromPort: '3389'
          ToPort: '3389'
          CidrIp: '0.0.0.0/0'
  AWSInstanceSGSelfRef:
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !Ref AWSInstanceSG
      IpProtocol: '-1'
      SourceSecurityGroupId: !Ref AWSInstanceSG
  AWSWIN:
    Type: AWS::EC2::Instance
    DependsOn:
      - AWSNATGW
    Properties:
      ImageId: !Ref 'WindowsAMI'
      InstanceType: 't2.micro'
      SubnetId: !Ref 'AWSSNPrivate'
      IamInstanceProfile: !Ref SSMInstanceProfile
      Tags:
        - Key: Name
          Value: 'AWS-WIN'
      SecurityGroupIds:
        - !Ref AWSInstanceSG
      KeyName: !Ref 'KeyPairName'
  AWSCENTOS:
    Type: AWS::EC2::Instance
    DependsOn:
      - AWSNATGW
    Properties:
      ImageId: !Ref 'CentosAMI'
      InstanceType: 't2.micro'
      SubnetId: !Ref 'AWSSNPrivate'
      IamInstanceProfile: !Ref SSMInstanceProfile
      Tags:
        - Key: Name
          Value: 'AWS-CENTOS'
      SecurityGroupIds:
        - !Ref AWSInstanceSG
      KeyName: !Ref 'KeyPairName'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install python3 -y
  AWSUBUNTU:
    Type: AWS::EC2::Instance
    DependsOn:
      - AWSNATGW
    Properties:
      ImageId: !Ref 'UbuntuAMI'
      InstanceType: 't2.micro'
      SubnetId: !Ref 'AWSSNPrivate'
      IamInstanceProfile: !Ref SSMInstanceProfile
      Tags:
        - Key: Name
          Value: 'AWS-Ubuntu'
      SecurityGroupIds:
        - !Ref AWSInstanceSG
      KeyName: !Ref 'KeyPairName'
  AWSJUMPBOX:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref 'AmazonLinux2AMI'
      InstanceType: 't2.micro'
      SubnetId: !Ref 'AWSSNPublic'
      Tags:
        - Key: Name
          Value: 'AWS-JUMPBOX'
      SecurityGroupIds:
        - !Ref AWSInstanceSG
      KeyName: !Ref 'KeyPairName'
  AWSVPCESSM:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: "Interface"
      PrivateDnsEnabled: "True"
      SubnetIds:
        - !Ref AWSSNPrivate
      SecurityGroupIds:
        - !Ref AWSInstanceSG
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcId: !Ref AWSVPC
  AWSVPCEEC2Messages:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: "Interface"
      PrivateDnsEnabled: "True"
      SubnetIds:
        - !Ref AWSSNPrivate
      SecurityGroupIds:
        - !Ref AWSInstanceSG
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      VpcId: !Ref AWSVPC
  AWSVPCESSMMessages:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: "Interface"
      PrivateDnsEnabled: "True"
      SubnetIds:
        - !Ref AWSSNPrivate
      SecurityGroupIds:
        - !Ref AWSInstanceSG
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      VpcId: !Ref AWSVPC
  AWSVPCESEC2:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: "Interface"
      PrivateDnsEnabled: "True"
      SubnetIds:
        - !Ref AWSSNPrivate
      SecurityGroupIds:
        - !Ref AWSInstanceSG
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2
      VpcId: !Ref AWSVPC
  AWSVPCES3:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds:
        - !Ref AWSRTPrivate
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: !Ref AWSVPC
  SSMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  SSMInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref SSMRole
Outputs:
  AWSVPC:
    Description: VPC ID of the AWS VPC
    Value: !Ref AWSVPC
    Export:
      Name: AWSVPC
  AWSSNPRIVATE:
    Description: AWS Private Subnet ID
    Value: !Ref AWSSNPrivate
    Export:
      Name: AWSSNPRIVATE
  AWSINSTANCESG:
    Description: AWS Instance Security Group ID
    Value: !Ref AWSInstanceSG
    Export:
      Name: AWSINSTANCESG
  AWSRTPRIVATE:
    Description: AWS PRIVATE RT ID
    Value: !Ref AWSRTPrivate
    Export:
      Name: AWSRTPRIVATE